name: CI

on:
    push:
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - '*.md'

permissions:
    contents: read

jobs:
    test:
        name: test
        if: github.event.pull_request.draft == false
        strategy:
            matrix:
                node: [14, 16, 18]
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Check out repo
              uses: actions/checkout@v3

            - name: Setup Node ${{ matrix.node }} on ${{ matrix.os }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: npm i --ignore-scripts

            - name: Run tests
              run: npm test

    # This job is used to save the PR number in an artifact, for use in the automerge.yml workflow
    save-pr-number:
        name: Save Dependabot PR Number
        if: >
            github.event.pull_request.draft == false &&
            github.event_name == 'pull_request' &&
            github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v3

            - name: Save PR number
              run: |
                  mkdir -p ./pr
                  echo ${{ github.event.number }} > ./pr/NR

            - name: Upload PR number in artifact
              uses: actions/upload-artifact@v3
              with:
                  name: pr
                  path: pr/
