name: CI

on:
    push:
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - '*.md'

jobs:
    test:
        name: test
        if: github.event.pull_request.draft == false
        strategy:
            matrix:
                node-version: [10, 12, 14, 16]
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm install --ignore-scripts
            - name: Run Tests
              run: npm test

    automerge:
        name: Automatically Merge Dependabot Pull Requests
        if: github.event.pull_request.draft == false
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v1.1.1
              if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
